---
title: "Principal"
output: html_document
---

# Dengue in Juiz de Fora

```{r}
library(tidyverse)
library(microdatasus)
library(read.dbc)
```

## Uploading and organizing dengue data
```{r}
# From 2013 forward

mg_dengue_2013_2019 <-list.files("C:\\Users\\Usuario\\Desktop\\João Pedro\\IC\\IC Clima e Doenças\\Projeto Arboviroses e Tempo\\all_arbo_data\\",
                                 pattern = "^DENGMG",
                                 full.names = T)
# gathering data from each year
big_tib <- tibble()
for (i in mg_dengue_2013_2019){
  print(paste0("Entering in ", i))
  storage <- read.dbc(i)
  big_tib <- bind_rows(big_tib, storage)
}
# processing data using microdatasus

mg_dengue_2013_2019_files <- big_tib  

mg_dengue_2013_2019_processed <- mg_dengue_2013_2019_files %>%
  process_sinan_dengue()

# saving 
saveRDS(mg_dengue_2013_2019_files, "mg_dengue_2013_2019_files.rds")

# getting data before 2013


br_dengue_before_2013 <- 
  list.files("C:\\Users\\Usuario\\Desktop\\João Pedro\\IC\\IC Clima e Doenças\\Dados\\Arquivos Dengue\\",
             pattern = "^DENG",
             full.names = T)

big_tib <- tibble()
for (i in br_dengue_before_2013[1:7]){
  print(paste0("Entering in ", i))
  storage <- foreign::read.dbf(i) %>% filter(SG_UF_NOT == "MG")
  big_tib <- bind_rows(big_tib, storage)
}


mg_dengue_2000_2006_files <- big_tib
saveRDS(mg_dengue_2000_2006_files, "mg_dengue_2000_2006_files.rds")

# data changed after 2007

big_tib <- tibble()
for (i in br_dengue_before_2013[8:13]){
  print(paste0("Entering in ", i))
  storage <- foreign::read.dbf(br_dengue_before_2013[13]) %>% filter(SG_UF_NOT == 31)
  big_tib <- bind_rows(big_tib, 
                       storage %>% # combine factor with numeric was a trouble
                         mutate(PLAQ_MENOR = PLAQ_MENOR %>% as.numeric()))
}

mg_dengue_2007_2012_files <- big_tib
saveRDS(mg_dengue_2007_2012_files, "mg_dengue_2007_2012_files.rds")

# these dataframes are to big to work, so we must select data that is going to be used
# first, selecting JF data

jf_deng_2000_2006 <- mg_dengue_2000_2006_files %>% filter(ID_MUNICIP == 3136702)
jf_deng_2006_2012 <- mg_dengue_2007_2012_files %>% filter(ID_MUNICIP == 313670)
jf_deng_2013_2019 <- mg_dengue_2013_2019_files %>% filter(ID_MUNICIP == 313670)

saveRDS(jf_deng_2000_2006,"jf_deng_2000_2006.rds")
saveRDS(jf_deng_2006_2012,"jf_deng_2006_2012.rds")
saveRDS(jf_deng_2013_2019,"jf_deng_2013_2019.rds")

bind_rows(jf_deng_2006_2012[,5] %>% view(), jf)




```

